name: github actions ci

on:
  push:
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: minimum
        uses: sarisia/actions-status-discord@v1.11.0-pre.0
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}

      - name: full options
        uses: sarisia/actions-status-discord@v1.11.0-pre.0
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          content: "Hey <@316911818725392384>"
          title: "deploy"
          description: "Build and deploy to GitHub Pages"
          image: ${{ vars.THINKING_IMAGE_URL }}
          color: 0x0000ff
          url: "https://github.com/sarisia/actions-status-discord"
          username: GitHub Actions
          avatar_url: ${{ vars.THINKING_IMAGE_URL }}

      - name: markdown
        uses: sarisia/actions-status-discord@v1.11.0-pre.0
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          nodetail: true
          color: 0xff96d5
          title: New version of `software` is ready!
          description: |
            Version `1.2.3-alpha`
            Click [here](https://github.com/sarisia/actions-status-discord) to download!
